IF (NOT EXISTS (SELECT TOP 1 1
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'GOT_USER'))
BEGIN
    
CREATE TABLE GOT_USER(    
    GOT_USER_ID int IDENTITY(1,1) NOT NULL,    
    GOT_USER_USERNAME nvarchar(100) NOT NULL,
    GOT_USER_PASSWORD nvarchar(250) NULL,
    GOT_USER_ACTIVE bit NOT NULL,
    GOT_USER_GUID uniqueidentifier ROWGUIDCOL  NULL,
    GOT_USER_CREATED_DATE datetime NULL,
    GOT_USER_LOGINFAIL int NULL,
    GOT_USER_PASSWORD_CHANGED datetime NULL,
    GOT_USER_EMAIL_CONFIRMED tinyint NOT NULL,
    GOT_USER_PHONE_NUMBER_CONFIRMED bit NOT NULL,
    GOT_USER_TWO_FACTOR_ENABLED bit NOT NULL,
    GOT_USER_LOCKOUT_END_DATE datetime NULL,
    GOT_USER_LOCKOUT_ENABLED bit NOT NULL,
    GOT_USER_SECURITY_STAMP nvarchar(max) NULL)
 
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_ACTIVE'))
BEGIN
    ALTER TABLE GOT_USER 
        ADD  CONSTRAINT DF_GOT_USER_GOT_USER_ACTIVE  
        DEFAULT (1) FOR GOT_USER_ACTIVE
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_GUID'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_GUID  DEFAULT (newid()) FOR GOT_USER_GUID
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_TF_USER_TF_USER_CREATED_DATE'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_TF_USER_TF_USER_CREATED_DATE  DEFAULT (getdate()) FOR GOT_USER_CREATED_DATE
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_LOGINFAIL'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_LOGINFAIL  DEFAULT (0) FOR GOT_USER_LOGINFAIL
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_PASSWORD_CHANGED'))
BEGIN
ALTER TABLE GOT_USER ADD CONSTRAINT DF_GOT_USER_GOT_USER_PASSWORD_CHANGED  DEFAULT (getdate()) FOR GOT_USER_PASSWORD_CHANGED
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_EMAIL_CONFIRMED'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_EMAIL_CONFIRMED  DEFAULT ((0)) FOR GOT_USER_EMAIL_CONFIRMED
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_PHONE_NUMBER_CONFIRMED'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_PHONE_NUMBER_CONFIRMED  DEFAULT ((0)) FOR GOT_USER_PHONE_NUMBER_CONFIRMED
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_TWO_FACTOR_ENABLED'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_TWO_FACTOR_ENABLED  DEFAULT ((0)) FOR GOT_USER_TWO_FACTOR_ENABLED
END
GO

IF (NOT EXISTS (SELECT TOP 1 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_NAME='DF_GOT_USER_GOT_USER_LOCKOUT_ENABLED'))
BEGIN
    ALTER TABLE GOT_USER ADD  CONSTRAINT DF_GOT_USER_GOT_USER_LOCKOUT_ENABLED  DEFAULT ((0)) FOR GOT_USER_LOCKOUT_ENABLED
END
GO
